# Generated by Django 3.0.8 on 2020-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='dn',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
